[package]
name = "d-inf"
version = "0.1.0"
authors = ["Aurelia Augusta <aurelia@aeva.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = "2.33.0"
crdts = "2.0.0"
rust-ini =  "0.13.0"
